name: CI
on:
  repository_dispatch:
    types: [wordpress]
jobs:
  wordpress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 7c9f21a941d03b6bf2466ef6e05d6f7530b1d8ee
          repository: m-malanowski/drewstal
          event-type: wordpress       
