name: CI
on:
  repository_dispatch:
    types: [wordpress]
jobs:
  wordpress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - name: executing remote ssh commands using password
        uses: fifsky/ssh-action@master
        with:
            host: '94.152.11.3'
            user:  h792087
            key: ${{ secrets.PRIV_DREWSTAL }}
            command: ls -lah

