# This is a basic workflow to help you get started with Actions
- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v1.1.2
  with:
   token:  7c9f21a941d03b6bf2466ef6e05d6f7530b1d8ee
   repository: m-malanowski/drewstal
   event-type: wordpress
   client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
---
name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
---
